name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Install AsciiDoc
    - name: Install Asciidoc
      run: sudo apt-get update && sudo apt-get install -y asciidoctor

    # Generate PDF from AsciiDoc source
    - name: Generate PDF
      run: asciidoctor-pdf documentation.adoc -o documentation.pdf

    # Upload PDF artifact
    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: documentation.pdf
